apiVersion: v1
kind: Pod
metadata:
  name: server
  labels:
    app.kubernetes.io/name: server
spec:
  containers:
  - name: server
    image: test-server:latest
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: curl
  labels:
    app.kubernetes.io/name: curl
spec:
  containers:
  - name: curl
    image: alpine/curl:latest
    command: ["sleep","3600"]
---
apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: node-server
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30303